maxSeq: maxSeq.o test-subseq.o
	gcc -o maxSeq -std=gnu99 -pedantic -Wall -Werror maxSeq.o test-subseq.o
maxSeq.o: maxSeq.c
	gcc -c -std=gnu99 -pedantic -Wall -Werror maxSeq.c
test-subseq.o: test-subseq.c
	gcc -c -std=gnu99 -pedantic -Wall -Werror test-subseq.c
